apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java
  name: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java
    spec:
      containers:
      - image: juhichoudhary/java-pipeline
        name: java-pipeline
        resources: {}
status: {}
