apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: java
  name: java
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: java
  type: NodePort
status:
  loadBalancer: {}
